---
- name: configure chrony package - Debian
  when: chronyinstalled is success
  template: src=chrony.conf.j2 dest=/etc/chrony/chrony.conf mode=0644
  notify:
    - restart chrony
    - start chrony
...