---
- name: start chrony
  systemd: name=chrony.service state=started
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: restart chrony
  systemd: name=chrony.service state=restarted
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- debug: msg='redhat'
  when: ansible_os_family == "RedHat" or ansible_distribution == "CentOS"
- name: start chronyd
  systemd: name=chronyd.service state=started
  when: ansible_os_family == "RedHat" or ansible_distribution == "CentOS"
- name: restart chronyd
  systemd: name=chronyd.service state=restarted 
  when: ansible_os_family == "RedHat" or ansible_distribution == "CentOS"
...
